#define OLD_MAIN_DIALOG             1000
#define TXT_DRIVELABEL              1001
#define CB_DRIVELIST                1002
#define TXT_DIRECTORYLABEL          1003
#define LB_DIRLIST                  1004
#define TXT_FILELABEL               1005
#define LB_FILELIST                 1006
#define TXT_CHOSENLABEL             1007
#define LB_CHOSENLIST               1008
#define PB_OPEN                     1009
#define PB_SAVE                     1010
#define PB_QUIT                     1011
#define PB_ADD                      1012
#define PB_REMOVE                   1013
#define PB_ABOUT                    1016
#define GRP_SELECTALL               1014
#define GRP_DESELECTALL             1015
#define PB_FILESELECTALL            1017
#define PB_CHOSENSELECTALL          1018
#define PB_FILEDESELECTALL          1019
#define PB_CHOSENDESELECTALL        1020
#define GRP_CHANGEORDER             1021
#define PB_MOVEUP                   1022
#define PB_MOVEDOWN                 1023
#define PB_SORTBYNAME               1024
#define PB_HELP                     1025
#define PB_SETTINGS                 1026
#define DLG_SPLASH                  2000
#define RECT_SPLASH                 2001
#define TXT_CURRPATH                1030
#define NEW_MAIN_DIALOG             3000
#define EF_CURRPATH                 1031

#define DLG_SETTINGS                4000
#define GRP_MAINWINCHOICE           4002
#define RAD_OLDWIN                  4003
#define RAD_NEWWIN                  4004
#define GRP_TOGGLES                 4005
#define CHK_EXITCONFIRM             4006
#define CHK_AUTOPOSSAVE             4007
#define PB_SAVEPOS                  4008
#define PB_SETOK                    4009
#define PB_SETCANCEL                4010
#define PB_SETHELP                  4011
#define PB_INCLUDE                  1027
